# Generated by Django 5.1.6 on 2025-02-08 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="post",
            new_name="board",
        ),
    ]
