# Generated by Django 5.1.6 on 2025-02-11 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0006_alter_chatmessage_table_conversation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="conversation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="board.conversation",
            ),
        ),
    ]
